name: first-workflow
on: workflow_dispatch
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run Script
        run: python ./src/app.py
