name: first-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greetings
        run: |
          echo "Hello World"
          echo "I have arrived"
      - name: Print Goodbyes
        run: |
          echo "Good Bye"
          echo "I'm done"
