name: first-workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Get info
        run: echo "${{toJSON(github)}}" 
  test:
    needs: info
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run Tests
        run: python test/dummy_tester.py
  run-script:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run Script
        run: python src/app.py

  build:
    needs: run-script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: update setuptools and wheel
        run: pip install --upgrade setuptools wheel
      - name: create build
        run: python setup.py bdist_wheel
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dummy-wheel
          path: dist/*.whl